import type { QuoteSnapshot } from "../../types/quote";

export function mapQuoteSnapshotToPayload(snapshot: QuoteSnapshot) {
  const quote = {
    status: snapshot.status,
    customer_id: snapshot.customerId,
    customer_name_snapshot: snapshot.customerName,
    customer_document_snapshot: snapshot.customerDocument,
    price_table_id: snapshot.priceTableId,
    discount_table_id: snapshot.discountTableId,
    freight_table_id: snapshot.freightTableId,
    handling_rate_table_id: snapshot.handlingRateTableId,
    policy_version_id: snapshot.policyVersionId,
    calculation_version: snapshot.calculationVersion,
    anticipated_payment: snapshot.anticipatedPayment,
    anticipated_discount_percentage: snapshot.anticipatedDiscountPercentage,
    freight_table_name_snapshot: snapshot.freightTableName,
    freight_zone_snapshot: snapshot.freightZone,
    load_type_snapshot: snapshot.loadType,
    handling_rate_per_ton_snapshot: snapshot.handlingRatePerTon,
    product_subtotal: snapshot.productSubtotal,
    freight_total: snapshot.freightTotal,
    handling_total: snapshot.handlingTotal,
    economy_total: snapshot.economyTotal,
    grand_total: snapshot.grandTotal,
    expires_at: null,
  };
  const items = snapshot.items.map((item) => ({
    display_order: item.displayOrder,
    product_id: item.productId,
    payment_term_id: item.paymentTermId,
    discount_rule_id: item.discountRuleId,
    product_name_snapshot: item.productName,
    category_name_snapshot: item.categoryName,
    weight_kg_snapshot: item.weightKg,
    payment_term_snapshot: item.paymentTerm,
    table_unit_price: item.tableUnitPrice,
    quantity: item.quantity,
    line_discount_percentage: item.lineDiscountPercentage,
    anticipated_discount_percentage: item.anticipatedDiscountPercentage,
    total_discount_percentage: item.totalDiscountPercentage,
    final_unit_price: item.finalUnitPrice,
    economy_per_unit: item.economyPerUnit,
    freight_per_unit: item.freightPerUnit,
    handling_per_unit: item.handlingPerUnit,
    product_subtotal: item.productSubtotal,
    freight_subtotal: item.freightSubtotal,
    handling_subtotal: item.handlingSubtotal,
    total: item.total,
  }));
  return { quote, items };
}
